"""empty message

Revision ID: 1240404577cd
Revises: 953e4cf06ae6
Create Date: 2021-05-04 18:25:16.956605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1240404577cd'
down_revision = '953e4cf06ae6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('artist_id', 'user_id')
    )
    op.drop_table('favoriteArtists')
    op.alter_column('users', 'profile_pic',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'profile_pic',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_table('favoriteArtists',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"favoriteArtists_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('artistId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artistId'], ['artists.id'], name='favoriteArtists_artistId_fkey'),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], name='favoriteArtists_userId_fkey'),
    sa.PrimaryKeyConstraint('id', name='favoriteArtists_pkey')
    )
    op.drop_table('favorites')
    # ### end Alembic commands ###
