"""empty message

Revision ID: ad9749de3aab
Revises: ffdc0a98111c
Create Date: 2021-05-03 19:44:51.165797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ad9749de3aab"
down_revision = "ffdc0a98111c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artists",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("profile_pic", sa.String(length=100)),
        sa.Column("apiId", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "chats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sender_id", sa.Integer(), nullable=False),
        sa.Column("reciever_id", sa.Integer(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("createdAt", sa.DateTime(), nullable=True),
        sa.Column("updatedAt", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["reciever_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "favorites",
        sa.Column("artist_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artists.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("artist_id", "user_id"),
    )
    op.add_column("users", sa.Column("birthday", sa.DateTime()))
    op.add_column(
        "users", sa.Column("first_name", sa.String(length=50), nullable=False)
    )
    op.add_column("users", sa.Column("gender", sa.String(length=15), nullable=False))
    op.add_column(
        "users", sa.Column("preffered_gender", sa.String(length=15), nullable=False)
    )
    op.add_column(
        "users", sa.Column("profile_pic", sa.String(length=100), nullable=False)
    )
    op.add_column("users", sa.Column("state", sa.String(length=15), nullable=False))
    op.add_column("users", sa.Column("zip_code", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "zip_code")
    op.drop_column("users", "state")
    op.drop_column("users", "profile_pic")
    op.drop_column("users", "preffered_gender")
    op.drop_column("users", "gender")
    op.drop_column("users", "first_name")
    op.drop_column("users", "birthday")
    op.drop_table("favorites")
    op.drop_table("chats")
    op.drop_table("artists")
    # ### end Alembic commands ###
